<img src="https://i.pinimg.com/564x/aa/55/41/aa5541d265687d1fb50d15e6088013d6.jpg" width="1200" height="150" align="center">

# **SESI 4** // *Numpy*
---


    Numpy Intro 
    How to import NumPy
    Why use NumPy?
    Terminology
    What is an array?
    What are the attributes of an array?
    What’s the difference between a Python list and a NumPy array?
    
         1. NumPy Initialization 
         2. Creating Ndarrays in NumPy
         3. Add, Remove, and Sort
         4. Multi-Dimensional Arrays
         5. ndim , shape and size
         6. Sorting Array
         7. Reshape
         8. Convert 1D to 2D
         9. Indexing and Slicing
         10. Creating Array from Existing Data  
         11. Copying
         12. Basic array Operation
         13. Broadcasting 
         14. More Array Operations
         15. Save Array into file
         16. Latihan Studi Kasus
         17. Matrices 
               Create Matrices 
               Matrix Aritmetic 
               Dot Product 
               Matrix Indexing 
               Matrix Aggregation 
               Transposing and Reshaping 
               N-Dimensional Array 
               Flatten N-Dimensional Array 
         Working with math Formulas 
         
 
 Absen : 
       
       
       

## **NUMPY INTRODUCTION**
---
>NumPy (Python Numerik) adalah ekstensi open source dari Python Numerical komputasi. 

    NumPy (Python Numerik) adalah ekstensi open source dari Python Numerical komputasi. 
    Alat ini dapat digunakan untuk menyimpan dan memproses matriks besar. 
    Numpy jauh lebih efisien daripada struktur nested list Python sendiri. 
    Ini mendukung operasi array dan matriks beberapa dimensi. 
    Selain itu juga menyediakan sejumlah besar perpustakaan matematika untuk operasi array 
    Dan digunakan di hampir setiap bidang sains dan teknik. 
    
    NumPy dari tahun 2005 dan membentuk semacam kode sumber terbuka dan dipelihara 
    dan dikembangkan oleh banyak kolaborator bersama-sama.

    NumPy API digunakan secara luas di Pandas, SciPy, Matplotlib, scikit-learn, scikit-image 
    dan sebagian besar paket ilmu data dan Python ilmiah lainnya.

    Pustaka NumPy berisi array multidimensi dan struktur data matriks (Anda akan menemukan informasi lebih 
    lanjut tentang ini di bagian selanjutnya). Ini menyediakan ndarray, objek array n-dimensi homogen, 
    dengan metode untuk beroperasi secara efisien di atasnya. NumPy dapat digunakan untuk melakukan 
    berbagai macam operasi matematika pada array. Itu menambahkan struktur data yang kuat ke Python 
    yang menjamin perhitungan yang efisien dengan array dan matriks dan itu memasok perpustakaan 
    besar fungsi matematika tingkat tinggi yang beroperasi pada array dan matriks ini.


<img src="https://i.ibb.co/HK3pbdm/numpy-base.webp" align="center">

<br>

sumber : Harris, C.R., Millman, K.J., van der Walt, S.J. et al. Array programming with NumPy. Nature 585, 357–362 (2020). https://doi.org/10.1038/s41586-020-2649-2 


### **Installing NumPy**
>If you already have Python, you can install NumPy with:


    conda install numpy

or

    pip install numpy


    !pip install numpy 

In [140]:
pip install numpy 

You should consider upgrading via the '/Users/iketutg/MyKetut/workspace_python/__H8-PYTN071/env_pytn071/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np 
np.__version__

'1.23.4'

### **How to import NumPy**
>Setiap kali Anda ingin menggunakan paket atau pustaka dalam kode Anda, Anda harus membuatnya dapat diakses terlebih dahulu.

Untuk mulai menggunakan NumPy dan semua fungsi yang tersedia di NumPy, Anda harus mengimpornya. Ini dapat dengan mudah dilakukan dengan pernyataan impor ini:

    import numpy as np

(Kami mempersingkat "numpy" menjadi "np" untuk menghemat waktu dan juga untuk menjaga standarisasi kode sehingga siapa pun yang bekerja dengan kode Anda dapat dengan mudah memahami dan menjalankannya.)

### **Why use NumPy?**
>Array NumPy lebih cepat dan lebih ringkas daripada list Python.

 Sebuah array mengkonsumsi lebih 
    sedikit memori dan jauh lebih nyaman untuk digunakan. NumPy menggunakan lebih sedikit memori 
    untuk menyimpan data dan menyediakan mekanisme untuk menentukan tipe data, 
    yang memungkinkan kode untuk dioptimalkan lebih jauh.
    
    Numpy adalah library aljabar linear untuk python 

In [61]:
b = list(range(10)) ##
b


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [141]:
## Adding Vector menggunakan pure python without numpy 
def pythonsum(n):
    a = b = list(range(n)) ## range returns a lazy sequence object - it does not return a list
    c = [] # out put 
    for i in range(len(a)):
        x = a[i] ** 2 
        y = b[i] ** 3 
        c.append(x + y )
    return c 

c = pythonsum(10)    
print(c)

In [143]:
## Adding Vector menggunakan pure python with numpy 
def numpysum(n):
    a = np.arange(n) ** 2 
    b = np.arange(n) ** 3 
    c=a+ b 
    return c


In [144]:
x = numpysum(10) 
print(x)


[  0   2  12  36  80 150 252 392 576 810]


In [148]:
## membandingkan kecepatan antara numpy dg List core python 
from datetime import datetime
size = 100
start = datetime.now()
c = pythonsum(size)
delta = datetime.now() - start
print("The last 2 elements of the sum", c[-2:])
print("PythonSum elapsed time in microseconds", delta.microseconds)

The last 2 elements of the sum [950796, 980100]
PythonSum elapsed time in microseconds 441


In [147]:
start = datetime.now()
c = numpysum(size)
delta = datetime.now() - start
print("The last 2 elements of the sum", c[-2:])
print("NumPySum elapsed time in microseconds", delta.microseconds)

The last 2 elements of the sum [950796 980100]
NumPySum elapsed time in microseconds 122


## **TERMINOLOGY**
---

### **What is an array?**
>Array adalah struktur data pusat dari library NumPy.

    
Ini adalah kisi nilai dan berisi informasi tentang data mentah, cara menemukan elemen, dan cara menafsirkan elemen. Ini memiliki kisi elemen yang dapat diindeks dengan berbagai cara. Semua elemen memiliki tipe yang sama, disebut sebagai tipe array d (tipe data).
    
Array dapat diindeks oleh tupel bilangan bulat non-negatif, dengan boolean, oleh array lain, atau dengan bilangan bulat. Rank dari array adalah jumlah dimensi. Bentuk array adalah tupel bilangan bulat yang memberikan ukuran array sepanjang setiap dimensi.

Salah satu cara kita dapat menginisialisasi array NumPy adalah dari daftar Python bersarang.

    a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Kita dapat mengakses elemen dalam array menggunakan tanda kurung siku. Saat Anda mengakses elemen, ingatlah bahwa pengindeksan di NumPy dimulai dari 0. Artinya, jika Anda ingin mengakses elemen pertama dalam array, Anda akan mengakses elemen “0”.

        print(a[0])

Keluaran:

        [1 2 3 4]

Informasi lebih lanjut tentang array

    array 1D, array 2D, ndarray, vektor, matriks

Anda mungkin kadang-kadang mendengar array yang disebut sebagai "ndarray," yang merupakan singkatan dari "array N-dimensi." Array N-dimensi hanyalah sebuah array dengan sejumlah dimensi. Anda mungkin juga mendengar 1-D, atau array satu dimensi, 2-D, atau larik dua dimensi, dan seterusnya.  
    
    * Kelas NumPy ndarray digunakan untuk mewakili matriks dan vektor. 
    * Vektor adalah array dengan satu kolom. 
    * sedangkan matriks  mengacu pada array dengan banyak kolom.

### **What are the attributes of an array?**
>Array biasanya merupakan wadah berukuran tetap dari item dengan jenis dan ukuran yang sama. Jumlah dimensi dan item dalam array ditentukan oleh bentuknya.



Bentuk array adalah tupel bilangan bulat non-negatif yang menentukan ukuran setiap dimensi.

Di NumPy, dimensi disebut sumbu. Ini berarti jika Anda memiliki array 2D yang terlihat seperti ini:

    [[0., 0., 0.],
    [1., 1., 1.]]

Array Anda memiliki 2 sumbu. Sumbu pertama memiliki panjang 2 dan sumbu kedua memiliki panjang 3.

Sama seperti objek kontainer Python lainnya, isi array dapat diakses dan dimodifikasi dengan mengindeks atau mengiris array. Array yang berbeda dapat berbagi data yang sama, sehingga perubahan yang dibuat pada satu array mungkin terlihat di array lain.

Atribut array mencerminkan informasi intrinsik ke array itu sendiri. Jika Anda perlu mendapatkan, atau bahkan mengatur, properti array tanpa membuat array baru, Anda sering dapat mengakses array melalui atributnya.

### **What’s the difference between a Python list and a NumPy array?**
>NumPy memberi Anda sejumlah besar opsi terkait numerik yang cepat dan efisien. Meskipun list Python dapat berisi tipe data yang berbeda dalam satu list, semua elemen dalam array NumPy harus tipe data yang sama (Jika int harus integer, jika string maka harus string semua data).

Operasi matematika yang dimaksudkan untuk dilakukan pada array tidak akan mungkin jika array tidak homogen.

###  **NumPy Basic**

#### *NumPy Initialization*

In [9]:
import numpy

In [10]:
numpy.array([1,2,3])

array([1, 2, 3])

In [11]:
# contoh import menggunakan asterik all 
from numpy import * 

In [12]:
array([1,2,3])

array([1, 2, 3])

In [13]:
# contoh menyingkan librany numpy sebagai np 
import numpy as np 
np.array([1,2,3])

array([1, 2, 3])

#### *Cek Version dari Numpy*

In [14]:
np.__version__  ## pengecekan version dari numpy 

'1.23.4'

#### *Cara Melihat Docstring Modul/Library Numpy*

In [15]:
print(np.__doc__)  ## melihat dari doc string modul / libray numpy 


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

#### *Contoh*

In [158]:
array1 = np.arange(100)

In [160]:
np.set_printoptions(threshold=500) #sys.maxsize

In [153]:
array2 = list(range(100)) 

In [159]:
print(array1)

[ 0  1  2 ... 97 98 99]


In [155]:
print(array2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


## **ARRAY**
---

### **Create Array**

In [ ]:
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

Untuk membuat array NumPy, kalian dapat menggunakan fungsi **np.array()**.

Yang perlu kalian lakukan untuk membuat array sederhana adalah dengan passing list ke dalamnya. Kalian juga dapat menentukan tipe data dalam List kalian.

In [16]:
import numpy as np

a = np.array([1, 2, 3])     # CONTOH NP.ARRAY()

In [17]:
a

array([1, 2, 3])

Sering ada kasus ketika kita ingin NumPy menginisialisasi nilai array untuk kita. NumPy menyediakan metode seperti ones(), zeros(), dan lain-lain untuk kasus ini. Kitahanya memberikan mereka sejumlah elemen yang kita inginkan untuk di-generate:

In [19]:
# you can easily create an array filled with 0s:

np.zeros(6)                 # CONTOH NP.ZEROS()

array([0., 0., 0., 0., 0., 0.])

In [20]:
# Or an array filled with 1s:

np.ones(6)                  # CONTOH NP.ONES()

array([1., 1., 1., 1., 1., 1.])

In [21]:
# Or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of the memory.

np.empty(6)                 # CONTOH NP.EMPTY()

array([1., 1., 1., 1., 1., 1.])

In [22]:
# You can create an array with a range of elements

print(np.arange(4))         # CONTOH NP.ARRANGE()
print(np.arange(0,10,2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


---
tambahan dari pak ketut

In [162]:
# membuat list 
my_list = list(range(5))
my_list
print(type(my_list))


<class 'list'>


In [163]:
array_1 = np.array(my_list)
print(type(array_1))
array_1


<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [83]:
print("array1 :\n",array_1)

array1 :
 [0 1 2 3 4]


In [164]:
# You can create an array with a range of elements
print(np.arange(4)) # start default = 0 , stop=4 , step default =1  
print(np.arange(1,10)) # start, stop , step default = 1 
print(np.arange(2,10,2)) # start 0 , Stop = 10 , step =2 

[0 1 2 3]
[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


---------

Apa yang dilakukan **arange([start],stop,[step])** adalah mengatur angka dari awal hingga berhenti, dalam langkah langkah. Inilah artinya untuk np.arange(0,10,2):

kembalikan daftar np mulai dari 0 hingga 10 tetapi jangan sertakan 10 dan tambahkan angka 2 setiap kali.

hal penting yang perlu diingat di sini adalah bahwa nomor pemberhentian tidak akan dimasukkan dalam daftar.

contoh lain:

In [165]:
print(np.arange(2,29,5))

[ 2  7 12 17 22 27]


### **Add, Remove, and Sort**

In [ ]:
np.append()
np.delete()
np.sort()

Jika kalian mulai dari array ini:

    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

Kalian bisa menambahkan elemen ke array kalian kapan saja dengan np.append(). Pastikan untuk menentukan array dan elemen yang ingin kalian sertakan.

In [166]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [167]:
arr = np.append(arr, [9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Kalian bisa menghapus elemen dengan np.delete(). Jika kalian ingin menghapus elemen di posisi 1 dari array kalian, kalian dapat menjalankan:

In [168]:
# menghapus index 1 
np.delete(arr, 1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10])

Mengurutkan elemen sederhana dengan **np.sort()**. Anda dapat menentukan axis, jenis, dan urutan saat Anda memanggil fungsi.
     
     np.sort(a, axis=-1, kind=None, order=None)

Jika kalian mulai dari array ini:

In [169]:
arrsort = np.array([2, 1, 5, 3, 7, 4, 6, 8]) 

Kalian dapat dengan cepat mengurutkan angka dalam urutan menaik dengan:

In [170]:
data = np.sort(arrsort)
print(data)

[1 2 3 4 5 6 7 8]


In [91]:
print(arrsort)

[2 1 5 3 7 4 6 8]


### **Shape and Size**

In [ ]:
ndarray.ndim()
ndarray.size()
ndarray.shape()

**ndarray.ndim**

    akan memberi tahu kalian jumlah axes, atau dimensi, dari array.

**ndarray.size**

    akan memberi tahu kalian jumlah total elemen array. Ini adalah produk dari elemen shape array.

**ndarray.shape**

    akan menampilkan tuple integer yang menunjukkan jumlah elemen yang disimpan di sepanjang setiap dimensi array. Jika, misalnya, kalian memiliki larik 2D dengan 2 baris dan 3 kolom, maka bentuk larik Anda adalah (2,3).

In [24]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [25]:
array_example.ndim

3

In [26]:
array_example.size

24

In [27]:
array_example.shape

(3, 2, 4)

In [28]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [29]:
arr_one.ndim

2

In [30]:
arr_one.size

5

In [31]:
arr_one.shape

(1, 5)

### **Multi-Dimensional Arrays**
>NumPy array memudahkan kita untuk membuat array multi-dimensi.

<img src="https://i.ibb.co/dDQnK4S/2DArray.png" align="center">


In [171]:
import numpy as np 
multi_list = [[0, 1, 2, 3], [10, 11, 12,13]]
print(type(multi_list))
multi_list

<class 'list'>


[[0, 1, 2, 3], [10, 11, 12, 13]]

In [172]:
a = np.array(multi_list)
print(type(a))
print(a.ndim)
a.shape

<class 'numpy.ndarray'>
2


(2, 4)

#### ndim , shape and size

In [94]:
### sebelum 2 dimensi kita lakukan 1 dimensi

In [173]:
arr_1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])  # 1 dimensi
print(arr_1)

[2 1 5 3 7 4 6 8]


In [174]:
arr_1.ndim # Untuk mengetahui jumlah dimensi pada data menggunakan fungsi ndim.

1

In [175]:
arr_1.shape # Array a memiliki shape ...5, yaitu panjang array pada 1-dimensi array.

(8,)

In [176]:
arr_1.size

8

  ndarray.ndim akan memberi tahu Anda jumlah sumbu, atau dimensi, dari array.

  ndarray.size akan memberi tahu Anda jumlah total elemen array. Ini adalah produk dari elemen bentuk array.

  ndarray.shape akan menampilkan tupel bilangan bulat yang menunjukkan jumlah elemen yang disimpan di sepanjang setiap dimensi array. Jika, misalnya, Anda memiliki array 2D dengan 2 baris dan 3 kolom, bentuk array Anda adalah (2,3).

 *Fungsi shape pada array multi-dimensi menghasilkan tuple berisikan 
     **(jumlah baris, jumlah kolom)** .* 

<img src="https://i.ibb.co/LRLN7ZP/shape.png" align="center">

In [177]:
print(a)

[[ 0  1  2  3]
 [10 11 12 13]]


In [178]:
# Pada fungsi shape menghasilkan sebuah tuple yang berisikan panjang sebuah array pada tiap dimensi.
a.shape 

(2, 4)

  Untuk mengetahui jumlah elemen pada array multi-dimensi menggunakan fungsi size.

<img src="https://i.ibb.co/KN199JW/size.png" align="center"> 

In [101]:
a.size

8

    Untuk mengetahui jumlah dimensi dari array multi-dimensi menggunakan fungsi ndim. Jumlah dimensi pada array a adalah 2, karena merupakan array 2-dimensi.

In [102]:
a.ndim

2

In [179]:
# 3 dimensi 
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [180]:
array_example.ndim

3

In [181]:
array_example.shape 

(3, 2, 4)

In [182]:
array_example.size 

24

-----------

    Pada array multi-dimensi kita dapat mengakses nilai elemen berdasarkan indeks dengan pemisah tanda koma [,]. 
    Misalkan kita ingin mendapatkan data pada baris ke-1 dan kolom ke-3 dari array a,
    maka dilakukan perintah a[1, 3].

    Misalkan, kita akan mengganti data pada baris ke-1 dan kolom ke-3 pada array a dengan nilai -1, 
    kita dapat langsung assign nilai baru tersebut pada indeks.

<img src="https://i.ibb.co/LPDSf6N/2dimx.png" align="center"> 

In [183]:
print(a)

[[ 0  1  2  3]
 [10 11 12 13]]


In [184]:
a[1,3]

13

In [185]:
a[1,3] = -1 
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

 #### Sorting Array
 
 np.sort?  ## Signature: np.sort(a, axis=-1, kind=None, order=None)

 ----------------------------------
|   kind    |  speed  |    stable |
|:--------|:-------|:--------| 
|'quicksort' |   1    |          no |
|'heapsort'  |   3   |          no |
|'mergesort' |   2   |       yes |
|'timsort'   |   2  |          yes |


In [186]:
data = np.array([[4, 1, 0, 5],[1, 5, 3, 4]])
data

array([[4, 1, 0, 5],
       [1, 5, 3, 4]])

 a = np.array([[1,4],[3,1]])

>>> np.sort(a)                # sort along the last axis

array([[1, 4],
       [1, 3]])

>>> np.sort(a, axis=None)     # sort the flattened array

array([1, 1, 3, 4])

>>> np.sort(a, axis=0)        # sort along the first axis
array([[1, 1],
       [3, 4]])

In [187]:
# menambahkan parameter axis =1 
data.sort(axis=1)
print(data)

[[0 1 4 5]
 [1 3 4 5]]


In [112]:
## dengan kita menambahkan parameter "axis=0" kita menghasilkan 
## array baru yang merupakan hasil sorting berdasarkan per kolom 

In [188]:
data = np.array([[4, 1, 0, 5],[1, 5, 3, 4]])
# menambahkan parameter axis =0 
print(data)
print("sebelum di sort axis=0")
print(10*"=====")
data.sort(axis=0)
print(data)

[[4 1 0 5]
 [1 5 3 4]]
sebelum di sort axis=0
[[1 1 0 4]
 [4 5 3 5]]


In [114]:
## dengan kita menambahkan parameter "axis=0" kita menghasilkan 
## array baru yang merupakan hasil sorting berdasarkan per kolom 

In [189]:
# menambahkan parameter axis =1 
data.sort(axis=1)   ## data ini adalah hasil perubahan dari sebelumnya 
print(data)

[[0 1 1 4]
 [3 4 5 5]]


______

In [190]:
#### sorting dengan membuat structure array
dtype = [('name', 'S10'), ('height', float), ('age', int)]  ##  name type string , heigh type float , age type int
dtype 

[('name', 'S10'), ('height', float), ('age', int)]

In [191]:
values = [('Arthur', 1.8, 41), 
          ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
values 

[('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [192]:
a = np.array(values, dtype=dtype) # create a structured array
print(a)

[(b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38) (b'Galahad', 1.7, 38)]


In [193]:
x = np.sort(a, order='name')  
print(x)

[(b'Arthur', 1.8, 41) (b'Galahad', 1.7, 38) (b'Lancelot', 1.9, 38)]


In [194]:
np.sort(a, order=['age', 'height'])     

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [121]:
values[1] # menghasilkan tuple 


('Lancelot', 1.9, 38)

In [122]:
values[0][0] ## arthur , 

'Arthur'

#### zeroes 

  Sering ada kasus ketika kita ingin NumPy menginisialisasi nilai array untuk kita. NumPy menyediakan metode seperti one(), zeros(), dan lain-lain untuk kasus ini. Kami hanya memberikan mereka jumlah elemen yang kami ingin hasilkan: 

In [123]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [124]:
# Or an array filled with 1s:

np.ones(2)

array([1., 1.])

In [195]:
# Atau bahkan array kosong!
# Fungsi kosong membuat larik yang konten awalnya acak dan bergantung pada status memori.
np.empty(3) # lakukan perubahan parameter

array([1.7, 1.9, 1.8])

In [196]:
dzero = np.zeros((2,2,2))
print(dzero)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [127]:
dzero.shape

(2, 2, 2)

In [128]:
dzero.ndim

3

In [129]:
zeros_ndarray = np.zeros((3, 6))
zeros_ndarray

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [130]:
zeros_ndarray.shape

(3, 6)

In [131]:
zeros_ndarray.ndim

2

In [132]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [133]:
empty_array = np.empty((4, 3, 2))
empty_array

array([[[0.00000000e+000, 2.68677908e+154],
        [8.39911598e-323, 0.00000000e+000],
        [2.12199579e-314, 5.02034658e+175]],

       [[1.32324163e-071, 5.44207827e-062],
        [6.56196567e+169, 9.59405921e-071],
        [1.09287130e-042, 7.11767117e-144]],

       [[3.59751658e+252, 1.46901661e+179],
        [3.75505006e+199, 2.59027921e-144],
        [3.80985069e+180, 4.90746474e+252]],

       [[3.96041428e+246, 1.16318408e-028],
        [9.16448945e-072, 4.08468727e+179],
        [1.90253394e+185, 1.27888305e+161]]])

In [134]:
empty_array.ndim

3

In [135]:
empty_array.shape

(4, 3, 2)

________

### **Reshape**
>Menggunakan **np.reshape()** akan memberikan bentuk baru ke array tanpa mengubah data.

Ingatlah bahwa ketika Anda menggunakan metode reshape.  
>output dari array memiliki jumlah elemen yang sama dengan array aslinya.

     12 element :  4x3 , 3x4 , 12 x 1 
    
Dengan np.reshape, Anda dapat menentukan beberapa parameter opsional:

    numpy.reshape(a, newshape, order)

keterangan :
- a : array yang akan dibentuk kembali.
- newshape :
    - int atau tuple dari ints
    - bentuk baru yang Anda inginkan. 
    - Anda dapat menentukan bilangan bulat atau tupel bilangan bulat. 
    - Jika Anda menentukan bilangan bulat, hasilnya akan berupa array dengan panjang tersebut. 
    - Bentuknya harus sesuai dengan bentuk aslinya.
- order    :
    - 'C' berarti membaca/menulis elemen menggunakan urutan indeks seperti C,
    - 'F' berarti membaca/menulis elemen menggunakan urutan indeks seperti Fortran, 
    - 'A' berarti membaca/menulis elemen dalam seperti Fortran urutan indeks jika a adalah Fortran bersebelahan dalam memori, urutan seperti C sebaliknya. 
    (Ini adalah parameter opsional dan tidak perlu ditentukan.)

Default = C 

Jika kalian mulai dengan array ini:

In [33]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


Anda dapat menggunakan reshape() untuk membentuk kembali array Anda.

**CONTOH KASUS :**

>Anda dapat membentuk ulang array ini menjadi array dengan tiga baris dan dua kolom:

In [34]:
a.reshape(2,3)

[[0 1 2]
 [3 4 5]]


In [35]:
##For example, ``a.reshape(10, 11)`` is equivalent to ``a.reshape((10, 11))``
a.reshape((3,2))

[[0 1]
 [2 3]
 [4 5]]


In [49]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [40]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [47]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [58]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [59]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

### **Convert 1D to 2D**
>Anda dapat menggunakan np.newaxis dan np.expand_dims untuk meningkatkan dimensi array yang ada.

In [ ]:
np.newaxis          # menambah 1 dimensi tiap digunakan
np.expand_dims      # memperluas array dg nambah axis baru

 Menggunakan np.newaxis akan meningkatkan dimensi array Anda satu dimensi saat digunakan sekali.
Artinya :
- Array 1D akan menjadi array 2D,
- Array 2D akan menjadi Array 3D, dan seterusnya.

Misalnya, jika Anda mulai dengan array ini:

In [71]:
variabelA = np.array([1, 2, 3, 4, 5, 6])
variabelA.shape

(6,)

In [72]:
# You can use np.newaxis to add a new axis:
# menambahkan menggunakan np.newaxis 
a2 = variabelA[np.newaxis]          # CONTOH NEWAXIS()
print(a2.shape)
print(a2)
a2.ndim

(1, 6)
[[1 2 3 4 5 6]]


2

In [73]:
# Anda dapat mengonversi array 1D ke vektor baris dengan 
# memasukkan sumbu di sepanjang dimensi pertama
row_vector = variabelA[np.newaxis, :]   # CONTOH NEWAXIS()
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [74]:
# untuk vektor kolom, Anda dapat menyisipkan axis di sepanjang
# dimensi kedua

col_vector = a[:, np.newaxis]           # CONTOH NEWAXIS()
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


kita juga dapat memperluas array dengan menyisipkan axis baru pada posisi tertentu dengan np.expand_dims.

Misalnya, jika Anda mulai dengan array ini:

In [75]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [76]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)       # CONTOH EXPAND_DIMS()
b.shape
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [77]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)       # CONTOH EXPAND_DIMS()
print(c.shape)
print(c)

(1, 6)
[[1 2 3 4 5 6]]


### **Indexing and Slicing**
>Kalian dapat mengindeks dan slice array NumPy dengan cara yang sama seperti kalian slice lists Python.

Array NumPy juga mendukung slice, seperti kalian slice lists Python, dengan menggunakan operator titik dua (yaitu arr[:]) untuk mengiris. Kita juga dapat menggunakan pengindeksan negatif untuk mengiris ke arah belakang.

Kode di bawah ini menunjukkan potongan contoh array NumPy 1-D.

In [80]:
data = np.array([1,2,3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:]) ##  -2:   = posisi -2 sampai akhir 

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [81]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[:])

[1 2 3 4 5]


In [82]:
print((arr[1:]))

[2 3 4 5]


In [83]:
print((arr[2:4]))

[3 4]


In [84]:
print(repr(arr[:-1])) # array([1, 2, 3, 4])

array([1, 2, 3, 4])


In [85]:
print(repr(arr[-2:])) # array([4, 5])

array([4, 5])


Kita mungkin ingin mengambil bagian dari array atau elemen array tertentu untuk digunakan dalam analisis lebih lanjut atau operasi tambahan. 

- Untuk melakukannya, Anda harus membuat subset, mengiris, dan/atau mengindeks array Anda.
- Jika Anda ingin memilih nilai dari array Anda yang memenuhi kondisi tertentu, langsung saja dengan NumPy.

Misalnya, jika Anda mulai dengan array ini:

In [86]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [87]:
# mencetak semua nilai dalam array yang lebih dari
# sama dengan 5
print(a[a>=5]) 

[ 5  6  7  8  9 10 11 12]


**CONTOH KASUS :**
>Angka yang sama dengan atau lebih besar dari 5, dan menggunakan kondisi tersebut untuk mengindeks array.

In [88]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5]) 

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [89]:
# memilih elemen yang habis dibagi 2
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [90]:
# memilih elemen yang memenuhi dua kondisi menggunakan
# bitwise & dan | operator

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


### **Creating Array from Existing Data**
>Anda dapat dengan mudah menggunakan buat array baru dari bagian array yang ada.

slicing indexing

In [ ]:
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

Anda dapat dengan mudah menggunakan buat array baru dari bagian array yang ada. Katakanlah Anda memiliki array ini:

    array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Anda dapat membuat array baru dari bagian array Anda kapan saja dengan menentukan di mana Anda ingin mengiris array Anda.

In [228]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

Anda juga dapat menumpuk dua array yang ada, baik secara vertikal maupun horizontal. Katakanlah Anda memiliki dua array:

    a_1:

In [91]:
array([[1, 1],
     [2, 2]])


array([[1, 1],
       [2, 2]])

    a_2:

In [92]:

array([[3, 3],
     [4, 4]])


array([[3, 3],
       [4, 4]])

Kalian dapat menumpuk secara vertikal dengan vstack

In [95]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [96]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [97]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [98]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [93]:
a = np.array([1,2, 3])
b = np.array([2, 3, 4])

np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [99]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
print(a)
print(5*"==")
print(b)
np.vstack((a,b))

[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]


array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [103]:
a_2 = np.array([[3, 3],
                [4, 4]])
a_2

array([[3, 3],
       [4, 4]])

In [104]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_1

array([[1, 1],
       [2, 2]])

In [102]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

- Anda dapat membagi sebuah array menjadi beberapa array yang lebih kecil menggunakan **hsplit**. 
- Anda dapat menentukan jumlah array berbentuk sama untuk dikembalikan atau kolom setelah pembagian harus dilakukan.

Katakanlah Anda memiliki array ini:

    array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [105]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


    Jika panjang tidak sesuai 
```
<ipython-input-54-f668532b9a75>:1: VisibleDeprecationWarning:
- Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.
- If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
  ```

In [238]:
# membagi array ini menjadi tiga array yang sama bentuknya
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

Kalian dapat menggunakan metode view untuk membuat objek array baru yang terlihat sama dengan array asli (shallow copy)

In [106]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
# Using the copy method will make a complete copy of the array
# and its data (a deep copy).
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### **Copying**
>Jika tidak ingin merubah nilai asli menggunakan fungsi copy() 

Serupa dengan List Python, pada saat membuat referensi ke array NumPy, itu tidak membuat array yang berbeda. Oleh karena itu, jika kita mengubah nilai menggunakan variabel referensi, itu juga mengubah array asli.

- Jika tidak ingin merubah nilai asli menggunakan fungsi copy() 
- Fungsi tidak memiliki argumen yang diperlukan, dan mengembalikan array yang disalin.

Dalam contoh kode di bawah ini :
- c adalah referensi ke while d adalah salinannya.
- Oleh karena itu, perubahan c menyebabkan perubahan yang sama pada a,
- sedangkan perubahan d tidak mengubah nilai b.

In [109]:
x = [0,1]
y = [9,8]
z = x

print(x)
z[0] = 5 
print(x)

[0, 1]
[5, 1]


In [111]:

p = y.copy()
p[0] = 6 
print(y)  #tidak berubah 
print(p)

[9, 8]
[6, 8]


In [112]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))
print('Array b: {}'.format(repr(d)))


Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])
Array b: array([6, 8])


### **Basic array operations**

    Addition, subtraction, multiplication, division, and more

Setelah Anda membuat array, Anda dapat mulai bekerja dengannya.

**CONTOH KASUS :**
>Anda telah membuat dua array, satu disebut "data" dan satu lagi disebut "ones". Anda dapat menambahkan array bersama dengan tanda plus.

    data + ones

Anda tentu saja dapat melakukan lebih dari sekadar penambahan.

    data - data
    data * data
    data / data
    
Operasi dasar sederhana dengan NumPy. Jika Anda ingin menemukan jumlah elemen dalam array, Anda akan menggunakan **sum()**. Ini berfungsi untuk larik 1D, larik 2D, dan larik dalam dimensi yang lebih tinggi.

In [113]:
a = np.array([1, 2, 3, 4])

# menambahkan semua elemen dalam array
a.sum()

10

Untuk menambahkan baris atau kolom dalam array 2D, kita harus menentukan axis 

Jika kalian mulai dengan array ini:

In [114]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [115]:
# Anda dapat menjumlahkan baris
b.sum(axis=0)

array([3, 3])

In [117]:
# Anda dapat menjumlahkan kolom
b.sum(axis=1)

array([2, 4])

In [118]:
data = np.array([1,2])
data

array([1, 2])

In [119]:
ones = np.ones(2)
ones

array([1., 1.])

In [120]:
data + ones

array([2., 3.])

In [121]:
data * data

array([1, 4])

In [122]:
newdata = data / data 

newdata+ones

array([2., 2.])

### **Broadcasting**
>Ada kalanya Anda mungkin ingin melakukan operasi antara array dan satu angka (juga disebut operasi antara vektor dan skalar) atau antara array dengan dua ukuran berbeda.

**CONTOH KASUS :**
>Array Anda (kami akan menyebutnya "data") mungkin berisi informasi tentang jarak dalam mil tetapi Anda ingin mengubah informasi tersebut menjadi kilometer.

Anda dapat melakukan operasi ini dengan:

In [124]:
data * 1.6

array([1.6, 3.2])

<img src="https://i.ibb.co/t3Y0GvK/broadcast.png" align="left"> 

>NumPy memahami bahwa perkalian harus terjadi dengan setiap sel. Konsep itu disebut broadcasting.

>Broadcasting adalah mekanisme yang memungkinkan NumPy untuk melakukan operasi pada array dari berbagai bentuk. 

Dimensi array Anda harus kompatibel, misalnya, ketika dimensi kedua array sama atau ketika salah satunya adalah 1.

Jika dimensi tidak kompatibel, Anda akan mendapatkan kesalahan nilai.

In [125]:
print(data)
print(data * 2) 

[1 2]
[2 4]


### **More Array Operations** 

- Maximum
- minimum
- sum
- mean
- product
- standard deviation, and more

NumPy juga melakukan fungsi agregasi. Selain **min, max**, dan **sum**,  Anda dapat dengan mudah menjalankan **mean** untuk mendapatkan rata-rata, **prod** untuk mendapatkan hasil perkalian elemen, **std** untuk mendapatkan standar deviasi, dan banyak lagi.

In [ ]:
data.max()
data.min()
data.sum()

In [ ]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


    Sangat umum untuk ingin menggabungkan sepanjang baris atau kolom. Secara default, setiap fungsi agregasi NumPy akan mengembalikan agregat dari seluruh array.

In [ ]:
A.sum()


4.8595784

In [ ]:
A.min()


0.05093587

In [ ]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [ ]:
A.min(axis=0)


array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [ ]:
A.max()

0.82485143

In [ ]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [ ]:
A.std()

0.21392120766089617

 Empat nilai yang tercantum di atas sesuai dengan jumlah kolom dalam array Anda. Dengan array empat kolom, Anda akan mendapatkan empat nilai sebagai hasilnya.

In [ ]:
dataA = A.min(axis=1)
dataA

array([0.17296777, 0.05093587, 0.12697628])

In [ ]:
dataA.argmin()          # posisi index 

1

In [ ]:
dataA.argmax()          # posisi index 

0

### **Save Array Into File**

In [ ]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [ ]:
np.save("myarraytest2022.npy",A)

In [ ]:
responseFile = np.load('myarraytest2022.npy')
print(responseFile)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


## **FUNCTION**
---

Beberapa fungsi utilitas dasar dari modul np.random :
- np.random.seed
- np.random.shuffle

Kami menggunakan fungsi **np.random.seed** untuk mengatur random seed, yang *memungkinkan kami untuk mengontrol output* dari fungsi pseudo-random.

Fungsi mengambil satu bilangan bulat sebagai argumen, yang mewakili random seed.

Kode di bawah ini menggunakan np.random.seed dengan seed random yang sama. Perhatikan bagaimana output dari 
fungsi random di setiap proses berikutnya adalah identik ketika ditetapkan random seed yang sama.
Beberapa fungsi utilitas dasar dari modul np.random adalah np.random.seed dan np.random.shuffle. 

Dalam menggunakan fungsi np.random.seed untuk mengatur random seed, yang memungkinkan dilakukan 
untuk mengontrol output dari fungsi pseudo-acak. Fungsi mengambil satu bilangan bulat sebagai argumen, 
yang mewakili random seed.

Kode di bawah ini menggunakan np.random.seed dengan seed acak yang sama.

Perhatikan bagaimana output dari fungsi random di setiap proses berikutnya adalah identik ketika 
kita menetapkan random seed yang sama.

#### **zeros**

In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

#### **ones**

In [ ]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

#### **full**

In [ ]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

#### **eye**

In [ ]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

#### **Random**

In [264]:
print(np.random.randint(30))

3


In [260]:
np.random.seed(0)
print(np.random.randint(10))

5


In [269]:
random_arr = np.random.randint(10,100,6) # dari 10 ke 100 sebanyak 6 
print(random_arr)

[89 57 74 92 98 59]


In [271]:
np.random.seed(0)
random_arr = np.random.randint(3, high=100,
                               size=(2, 2)) ## randint(low, high=None, size=None, dtype=int)

print(repr(random_arr))



array([[47, 50],
       [67, 70]])


In [272]:

# New seed
np.random.seed(2)

random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))


array([[43, 18],
       [75, 25]])


In [273]:

# Original seed
np.random.seed(0)
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

array([[47, 50],
       [67, 70]])


### **LATIHAN PRAKTIKUM 1**
---


* Buat lah Array 
```
[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]
``` 

Simpan file Array tersebut 
Kemudian lakukan load file Array 

lakukan pencarian data dibawah ini 

Temukan Nilai minum dan maksimum pada file tersebut 

Temukan Nilai minum di setiap kolom 
Temukan Nilai Maksimum di setiap Kolom 
Menemukan Nilai Minimum di setiap baris 
Menemukan Nilai Maksimum di setiap baris 

In [ ]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(arr)

In [ ]:
np.save("myarray3.npy",arr)


In [ ]:
resfile = np.load('myarray3.npy')
print(resfile)

In [ ]:
print(resfile.min())
print(resfile.max())

print(repr(resfile.min(axis=0)))
print(repr(resfile.max(axis=0)))

print(repr(resfile.max(axis=-1)))
print(repr(resfile.min(axis=-1)))



----------

### **LATIHAN STUDI KASUS**
---

10 buah botol minum akan dibuat untuk menyimpan air dengan jari2 dan tinggi yang berbeda - beda . 
Besaran jari2 dan tinggi botol adalah bilang bulat kisaran 7 sampai dengan 20 cm . 

Temukan : 

1. Volume air yang dapat disimpan di setiap botol 
2. Total volume air yang tersimpan dalam semua botol 
3. Botol mana yang volume air terkecil dan temukan volumenya 
4. Botol mana yang menampung volume air terbesar dan temukan volume airnya . 
5. Rata-rata volume yang dapat di tampung di tiap botol 

Solusi : 
1. Lakukan generate tinggi botol dan jari2 
2. Punya batasan 7 sampai 20 , kemudian sebanyak 10 
   Dengan kata lain harus mengenerate sebanyak 20 
3. Membentuk botol sebanyak 10 buah (tinggi dan jari2) 
4. Setelah terbentuk botol mencari volume air masing botol 
   Volume air = (Pi x r^2 x t ) untuk numpy pi = np.pi 
5. Mencari Total volume air dalam semua botol sum 
6. Mencari botol yang terkcil dan temukan volume nya 
7. Mencari botol yang terbesar dan temukan volume nya 
8. Mencari rata2 dengan mean 

In [286]:
import numpy as np 
np.random.seed(0)
dataBotol = np.random.randint(7,20,20)
print(dataBotol)

[19 12  7 10 18 10 14 16 10 12  9 11 14 13 15 15 19 17  8 13]


In [ ]:
dataBotol.resize(10,2)
print(dataBotol)

In [ ]:
## tinngi kolom = 0
## jari kolom =1 
volume = np.pi * dataBotol[:,1]**2 * dataBotol[:,0]
print(volume)

In [ ]:
totalVolume = volume.sum()
print(f"Total volume  : {totalVolume} ")


In [ ]:
volume.argmin() # 
volume[volume.argmin()]

In [ ]:
volume.argmax()
volume[volume.argmax()]

In [ ]:
idxBotolKecil = volume.argmin()
volumeBotolKecil = volume[idxBotolKecil]
print(f"Botol Terkecil Pada Botol index : {idxBotolKecil} volume {volumeBotolKecil}")
idxBotolBesar = volume.argmax()
volumeBotolBesar = volume[idxBotolBesar]
print(f"Botol Terkecil Pada Botol index : {idxBotolBesar} volume {volumeBotolBesar}")


## **MATRICES**
---
>Anda dapat meneruskan list of list Python untuk membuat matriks untuk mewakilinya di NumPy.

### **Membuat Matriks**
>np.array([[1,2],[3,4]])

Kami juga dapat menggunakan metode yang sama yang kami sebutkan di atas (**ones()**, **zeros()**, dan **random.random()**) selama kami memberi mereka tupel yang menjelaskan dimensi matriks yang kami buat

In [144]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.31887346, 0.680065  ],
       [0.74054642, 0.08522349],
       [0.92572509, 0.7866034 ]])

In [143]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.91884487 0.51973842]
 [0.36481454 0.59200795]
 [0.61818012 0.17130877]]


### **Matrix Arithmetic**
>Kita dapat menjumlahkan dan mengalikan matriks menggunakan operator aritmatika (+ - * / )  

Jika kedua matriks tersebut berukuran sama. 
Numpy menangani sebagai position-wise operations.

In [290]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [291]:
ones = np.ones([2,2]) 
print(ones)

[[1. 1.]
 [1. 1.]]


In [292]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [293]:
ones_row = np.ones([1,2])
print(ones_row)


[[1. 1.]]


In [ ]:
print(data + ones_row)

In [ ]:
data1 = np.array([[1,2],[3,4],[5,6]])
print(data1)

In [ ]:
print(data1 + ones_row)

In [ ]:
data2 = np.array([[1,2,3],[4,5,6]])
print(data2)

In [ ]:
print(data2 + ones_row)

In [ ]:
ones_row.shape?

In [ ]:
data2.shape

In [ ]:
data.shape

### **Dot Product**
>Perbedaan utama yang harus dibuat dengan aritmatika adalah kasus perkalian matriks menggunakan produk titik.

NumPy memberikan setiap matriks metode **dot()** yang dapat kita gunakan untuk melakukan operasi produk dot dengan matriks lain

In [146]:
np.dot

<function numpy.dot>

In [147]:
np.dot(3, 4)

12

In [148]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [149]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [145]:
a = np.arange(3*4*5*6).reshape((3,4,5,6)) 
print(a)

[[[[  0   1   2   3   4   5]
   [  6   7   8   9  10  11]
   [ 12  13  14  15  16  17]
   [ 18  19  20  21  22  23]
   [ 24  25  26  27  28  29]]

  [[ 30  31  32  33  34  35]
   [ 36  37  38  39  40  41]
   [ 42  43  44  45  46  47]
   [ 48  49  50  51  52  53]
   [ 54  55  56  57  58  59]]

  [[ 60  61  62  63  64  65]
   [ 66  67  68  69  70  71]
   [ 72  73  74  75  76  77]
   [ 78  79  80  81  82  83]
   [ 84  85  86  87  88  89]]

  [[ 90  91  92  93  94  95]
   [ 96  97  98  99 100 101]
   [102 103 104 105 106 107]
   [108 109 110 111 112 113]
   [114 115 116 117 118 119]]]


 [[[120 121 122 123 124 125]
   [126 127 128 129 130 131]
   [132 133 134 135 136 137]
   [138 139 140 141 142 143]
   [144 145 146 147 148 149]]

  [[150 151 152 153 154 155]
   [156 157 158 159 160 161]
   [162 163 164 165 166 167]
   [168 169 170 171 172 173]
   [174 175 176 177 178 179]]

  [[180 181 182 183 184 185]
   [186 187 188 189 190 191]
   [192 193 194 195 196 197]
   [198 199 200 201 202 203]


In [ ]:
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
print(b)

In [ ]:
np.dot(a, b)[2,3,2,1,2,2]

In [ ]:
sum(a[2,3,2,:] * b[1,2,:,2])

### **Matrix Indexing**
>Operasi pengindeksan dan pemotongan menjadi lebih berguna saat kita memanipulasi matriks

   ```np.array([[1, 2], [3, 4], [5, 6]])```

    
<img src="https://i.ibb.co/4sS8HGD/Screen-Shot-2021-09-02-at-8-26-34-AM.png" align="left"> 

In [17]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print("data :")
print(data)
print((data[:]))
print("data[0,1] :")
print(data[0,1])
print("data[1:3] :")
print(data[1:3])
print("data[0:2] :")
print(data[0:2])
print("data[0:2,0] :")
print(data[0:2,0])
print("data[0:2,1] :")
print(data[0:2,1])

data :
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
data[0,1] :
2
data[1:3] :
[[3 4]
 [5 6]]
data[0:2] :
[[1 2]
 [3 4]]
data[0:2,0] :
[1 3]
data[0:2,1] :
[2 4]


In [21]:
print(data[:])
print(data[:, -1])

[[1 2]
 [3 4]
 [5 6]]
[2 4 6]


In [34]:
print(data[:, -1])         # -1 kanan (transpose)
xdata = data[:, -1]        # sama dengan data[:, -1]
xdata.ndim                  # cek jumlah dimensi
                            # xdata.shape

[2 4 6]


1

In [36]:
print(data[:, 1:])          # syntax : untuk transpose

[[2]
 [4]
 [6]]


In [37]:
print(data[:, 1:])          # -1 kanan
xdata = data[:, 1:]
xdata.ndim                  # 2 dimensi
                            #xdata.shape

[[2]
 [4]
 [6]]


2

In [38]:
print(data[:, :]) 

[[1 2]
 [3 4]
 [5 6]]


In [39]:
print(data[:, 0:1]) 


[[1]
 [3]
 [5]]


In [40]:
print(data[:, 1:2]) 

[[2]
 [4]
 [6]]


In [52]:
print(data[:, 1:]) 


[[2]
 [4]
 [6]]


In [41]:
print((data[0:2,:]))

[[1 2]
 [3 4]]


<img src="https://i.ibb.co/4sS8HGD/Screen-Shot-2021-09-02-at-8-26-34-AM.png" align="left"> 

In [51]:
print(repr(data[0:1, 1:]))

array([[2]])


In [46]:
print(repr(data))

array([[1, 2],
       [3, 4],
       [5, 6]])


In [47]:
print(repr(data[0:2, 1:]))

array([[2],
       [4]])


In [48]:
print(repr(data[1, 1:]))

array([4])


<img src="https://i.ibb.co/rQN75GL/numpy-indexing-arrays-width-1200.jpg" align="left"> 


In [53]:
np_m = np.arange(1,17)
np_m 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [54]:
np4x4 = np_m.reshape(4,4)
np4x4 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

<img src="https://i.ibb.co/rQN75GL/numpy-indexing-arrays-width-1200.jpg" align="left"> 


In [57]:
# baris 1 dan kolom 2:4 
npa = np4x4[1,2:4]
print(npa)
print(repr(npa))
print(5*"------")
# semua baris , hanya kolom 1 
npb = np4x4[:,1] 
print(npb)
print(repr(npb))


[7 8]
array([7, 8])
------------------------------
[ 2  6 10 14]
array([ 2,  6, 10, 14])


In [58]:
# baris 2 sampai akhir dan kolom 2 sampai akhir 
npc = np4x4[2: , 2:] 
print(npc) 
print(5*"-")
# baris 1  , sampai akhir , step 2  dan  kolom dari 0 sampai kolom akhir ,  step 2 
npd = np4x4[1::2, ::2] 
print(npd )

[[11 12]
 [15 16]]
-----
[[ 5  7]
 [13 15]]


### **LATIHAN PRAKTIKUM 2**

In [60]:
# membuat 2 array dengan shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
# menggunakan slicing untuk mendaptkan subarray yang terdiri dari :
# 2 baris pertama yaitu kolom 1 dan 2
# b adalah array bentuk berikut (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [63]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print((arr[:]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
print((arr[1:]))

[[4 5 6]
 [7 8 9]]


In [65]:
print(repr(arr[:, -1]))

array([3, 6, 9])


In [66]:
print(repr(arr[:, 1:]))     # (baris,kolom)


array([[2, 3],
       [5, 6],
       [8, 9]])


In [67]:
print(repr(arr[0:1,:]))

array([[1, 2, 3]])


In [68]:
print(repr(arr[0:1, 1:]))

array([[2, 3]])


In [69]:
print(repr(arr[0:2,:]))

array([[1, 2, 3],
       [4, 5, 6]])


In [70]:
print(repr(arr[0:2, 1:]))

array([[2, 3],
       [5, 6]])


In [71]:
print(repr(arr[0, 1:]))

array([2, 3])


### **Matrix Aggregation**
>Kita dapat menjumlahkan matriks dengan cara yang sama seperti kita menjumlahkan vector

In [72]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [73]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [74]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### **Transposing and Reshaping**
>Kebutuhan umum ketika berhadapan dengan matriks adalah kebutuhan untuk memutarnya.

Ini sering terjadi ketika kita perlu mengambil produk titik dari dua matriks dan perlu menyelaraskan dimensi yang mereka bagi. Array NumPy memiliki properti nyaman yang disebut T untuk mendapatkan transpos matriks.


mentraspose suatu array adalah proses mengubah posisi *element2 vektor baris menjadi vektor kolom demikian pula sebaliknya.* 

Menggunakan numpy , melakukan traspose suatu array dapat dilakukan dengan cara memangil function **transpose()** atau memanggil properti **T** dari suatu array  

In [306]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [307]:
print(data.transpose())

[[1 3 5]
 [2 4 6]]


In [75]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [77]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
print("")
data = data.transpose()
print(data)

[[1 2]
 [3 4]
 [5 6]]

[[1 3 5]
 [2 4 6]]


Dalam kasus penggunaan yang lebih lanjut, Anda mungkin perlu mengganti dimensi matriks tertentu. 

Ini sering terjadi dalam aplikasi pembelajaran mesin di mana model tertentu mengharapkan bentuk tertentu untuk input yang berbeda dari kumpulan data Anda.

Metode **reshape()** NumPy berguna dalam kasus ini. Anda hanya memberikan dimensi baru yang Anda inginkan untuk matriks. 

Anda dapat meneruskan -1 untuk suatu dimensi dan NumPy dapat menyimpulkan dimensi yang benar berdasarkan matriks Anda

In [78]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [79]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Anda juga dapat menggunakan **np.transpose** untuk membalikkan atau mengubah sumbu array sesuai dengan nilai yang Anda tentukan. Jika Anda mulai dengan array ini

In [81]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


Dalam banyak hal, berurusan dengan dimensi baru hanyalah menambahkan koma ke parameter fungsi NumPy 

In [82]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


### **N-Dimensional Array** 
>NumPy dapat melakukan semua yang telah kita sebutkan dalam sejumlah dimensi. Struktur data pusatnya disebut ndarray (N-Dimensional Array) karena suatu alasan.

<img src="https://miro.medium.com/max/799/0*G1IZA6_mFl3m9wH0.png?width=1920&dpr=2" width="700" align="center">

In [83]:

ndarr = np.array([ [[1,2],[3,4]],
                  [[5,6],[7,8]] ])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Dalam banyak hal, berurusan dengan dimensi baru hanyalah dengan menambahkan koma ke parameter fungsi NumPy

In [84]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [85]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [86]:
print(np.random.random((4,3,2)))

[[[0.50140065 0.64157961]
  [0.99488067 0.90076567]
  [0.36017669 0.93617081]]

 [[0.23048649 0.36734022]
  [0.85748303 0.15854157]
  [0.87136367 0.60115791]]

 [[0.8393793  0.60076345]
  [0.63357693 0.70012592]
  [0.34398875 0.61501061]]

 [[0.28610648 0.49981123]
  [0.98813338 0.93831509]
  [0.93598463 0.55491393]]]


### **Flatten N-Dimensional Array**
>Ada dua cara populer untuk meratakan array

Ada dua cara populer untuk meratakan array:
- .flatten()
- .ravel()

Perbedaan utama antara keduanya adalah bahwa array baru yang dibuat menggunakan ravel() sebenarnya adalah referensi ke array induk. Ini berarti bahwa setiap perubahan pada array baru akan mempengaruhi array induk juga. Karena ravel tidak membuat salinan, ini hemat memori.

In [87]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [88]:
# You can use flatten to flatten your array into a 1D array.
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [89]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## **WORKING WITH MATH FORMULAS**
---
>Menerapkan rumus matematika yang bekerja pada array adalah salah satu hal yang membuat NumPy sangat dihormati di komunitas Python ilmiah.  


**CONTOH KASUS :**
>Misalnya, ini adalah rumus mean square error (rumus utama yang digunakan dalam model pembelajaran mesin terawasi yang menangani regresi):

<img src="https://i.ibb.co/7tTftxS/Screen-Shot-2021-09-02-at-12-18-44-PM.png" width="300" align="center"> 

Menerapkan rumus ini sederhana dan mudah di Numpy :

In [ ]:
error = (1/n) * np.sum(np.square(observed - prediction)) 

------------

## **ADDITIONAL MATERI**
---

### *DATA STRUCTURE*

<img src="https://i.ibb.co/WK6XHvh/a-numpy-structure.png" align="left"> 


In [102]:
import numpy as np

# create array in sequence
np_a = np.arange(12)            # [0 1 2 3 4 5 6 7 8 9 10 11]
print(np_a)

# with initial value
print(np.arange(8, 16))         # [8 9 10 11 12 13 14 15]

# with step size
print(np.arange(1,10,2))        # [1 3 5 7 9]
print(np.arange(1,10,step=2))   # alternative method

# adding some operation
print(np.arange(7)+3)           # [3 4 5 6 7 8 9]
print(np.arange(7)-3)           # [-3 -2 -1 0 1 2 3]
print(np.arange(7)*3)           # [ 0 3 6 9 12 15 18]
print(np.arange(7)/3)           # [0 0 0 1 1 1 2]

# return the size of array
my_arange = np.arange(7)
print(my_arange.size)           # 7
print(len(my_arange))           # work with len()

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 8  9 10 11 12 13 14 15]
[1 3 5 7 9]
[1 3 5 7 9]
[3 4 5 6 7 8 9]
[-3 -2 -1  0  1  2  3]
[ 0  3  6  9 12 15 18]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.        ]
7
7


In [93]:
np_a.dtype      # cek tipe data variabel

dtype('int32')

In [94]:
np_a.shape      # cek bentuk/shape dari variabel

(12,)

In [103]:
np_a.strides

(4,)

In [104]:
# merubah menjadi 2 Dimensi dengan 4 baris dan 3 kolom 
np_2d = np_a.reshape(4,3)
np_2d 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [105]:
np_2d.shape

(4, 3)

In [106]:
np_2d.ndim

2

In [107]:
np_2d.dtype 

dtype('int32')

In [108]:
np_2d.strides

(12, 4)

In [109]:
# np_2d  int64 dengan locatannya 24 bytes 
np_2d = np_2d.astype('int16')   # astype() mengubah tipe data data
np_2d 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int16)

In [110]:
np_2d.strides

(6, 2)

### *INDEXING(VIEW)*

<img src="https://i.ibb.co/MS7b4kK/b-numpy-view.png" align="left"> 


In [111]:
np_2d[:,1:] # semua baris , kolom 1 dst (indeks mulai dari 0 )   [:,1::]  , [:,1::1] default step 1 

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]], dtype=int16)

In [313]:
np_2d[:, ::2]   # semua baris, kolom 0, sampai kolom terakhir,
                # dengan step 2 sesuai gambar diatas 

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

### *INDEXING(COPY)*

<img src="https://i.ibb.co/YN5XSDY/c-numpy-indexing-copy.png" align="left"> 


In [113]:
np_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int16)

In [112]:
np_2d[1,2]          # indeks skalar ; baris 1 kolom 2

5

In [115]:
np_2d[np_2d > 8]    # pengindeksan dengan condition 

array([ 9, 10, 11], dtype=int16)

In [116]:
np_2d[np_2d < 5] 

array([0, 1, 2, 3, 4], dtype=int16)

In [117]:
np_2d[[0,1] , [1,2]] # pengindeksan dengan array 

array([1, 5], dtype=int16)

In [119]:
np_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int16)

In [140]:
np_2d[ [[1],[2]], [1,0] ]   # kolom 1 dan 2 yang dipilih
                            # baris 1 dan 0 dibalik 

array([[4, 3],
       [7, 6]], dtype=int16)

### *VECTORIZATION*

<img src="https://i.ibb.co/Ybz0vBR/d-numpy-vectorization.png" align="left"> 


In [130]:
vectora = np.array([[0,1],[3,4],[6,7],[9,10]]) 
print("vector a")
print(vectora)

vector a
[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]]


In [129]:
vectorb = np.array([[1,1],[1,1],[1,1],[1,1]]) 
print("vector b")
print(vectorb)

vector b
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [128]:
vectorc = vectora + vectorb
print("vector c")
print(vectorc)

vector c
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


In [132]:
vectord = vectora + 1 
print("Vector d")
print(vectord)

Vector d
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


### *BROADCASTING*

<img src="https://i.ibb.co/M2s1TqC/e-numpy-broadcasting.png" align="left"> 


In [141]:
ebrodcast = np.array([[0], [3], [6], [9]])                                     
ebrodcast * np.array(*[[1, 2]])

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

### *REDUCTION*

<img src="https://i.ibb.co/FVbnhdc/f-numpy-reduction.png" align="left"> 

In [142]:
reduc = np.arange(12) 
print(reduc) 
reduc4x3  = reduc.reshape(4,3) 
print(reduc4x3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


<img src="https://i.ibb.co/QbjwCCD/numpy-reduction2.png" align="left"> 


In [143]:
one_d1 = reduc4x3.sum(axis=0)
print(one_d1)

one_d2 = reduc4x3.sum(axis=1)
print(one_d2)

skalar0d = reduc4x3.sum()
print(skalar0d)


[18 22 26]
[ 3 12 21 30]
66


### *EXAMPLE RESHAPE AND ARANGE*

In [145]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [146]:
x = x.reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [147]:
np.mean(x,axis=0)

array([4.5, 5.5, 6.5])

In [148]:
np.mean(x,axis=1)

array([ 1.,  4.,  7., 10.])

## **NUMPY READ CSV**
---

In [149]:
import csv

In [150]:
data = []

In [ ]:
with open('data/MER_T07_02A.csv', 'r') as csvfile:
    file_reader = csv.reader(csvfile, delimiter=',')
    for row in file_reader:
        data.append(row)
        
data = np.array(data)
#convert the list of lists to a NumPy array

In [315]:
data.shape

(8542, 6)

In [316]:
data[5]

array(['CLETPUS', '195313', '218846.325', '1',
       'Electricity Net Generation From Coal, All Sectors',
       'Million Kilowatthours'], dtype='<U80')

In [ ]:
data.dtype.type

In [317]:
np.save(open('data.npy', 'wb'), data)
# Saves data to a binary file with the .npy extension

In [319]:
newdata = np.load('data.npy')
newdata.shape

(8542, 6)